config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  validates :quantity, presence: true
  validates :ingredient_id, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes
  has_many :doses
  validates :name, presence: true, uniqueness: true, allow_blank: false
  validates :lipid, presence: true
  validates :carbohydrate, presence: true
  validates :protein, presence: true
  validates :kcal, presence: true
  validates :measure, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @dose = Dose.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @dose = Dose.new(dose_params)
    @dose.recipe = @recipe
    if @dose.save
      redirect_to recipe_path(@recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to doses_path, status: :see_other
  end

  private

  def dose_params
    params.require(:dose).permit(:quantity, :recipe_id, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:edit, :update, :destroy]
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.save
    redirect_to ingredient_path(@ingredient)
  end

  def edit
  end

  def update
    @ingredient.update(ingredient_params)
    redirect_to ingredient_path(@ingredient)
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_path, status: :see_other
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name, :lipid, :carbohydrate, :protein, :kcal, :measure)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    Recipe.new()
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.save
    redirect_to recipe_path(@recipe)
  end

  def edit

  end

  def update
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path, status: :see_other
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :ingredient)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/doses/new.html.erb
<%= simple_form_for [@recipe, @dose] do |f|%>
    <%= f.input :quantity %>
    <%= f.association :ingredient, prompt: "Select an ingredient"%>
    <%= f.submit  %>
  <% end %>

app/views/ingredients/index.html.erb
<section>
  <div class="top-head">
    <span></span>
    <h1>All ingredients</h1>
    <%= link_to "Add +", new_ingredient_path() %>
  </div>
  <div class="all">
    <div class="tbl-header">
      <table cellpadding="0" cellspacing="0">
        <thead>
          <tr>
            <th>Ingredients</th>
            <th>Protein</th>
            <th>Carbohydrate</th>
            <th>Lipid</th>
            <th>Kcal/100g</th>
          </tr>
        </thead>
      </table>
    </div>
    <div class="tbl-content">
      <table cellpadding="0" cellspacing="0" >
        <tbody>
            <% @ingredients.each do |ingredient| %>
              <tr>
                <td><%= link_to ingredient.name, ingredient_path(ingredient) %></td>
                <td><%= ingredient.protein %></td>
                <td><%= ingredient.carbohydrate %></td>
                <td><%= ingredient.lipid %></td>
                <td><%= ingredient.kcal %></td>
              </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/ingredients/new.html.erb
<section class="section-new-ingredient">
<%= simple_form_for(@ingredient) do |f|%>
    <div style="width: 100%;">
        <%= f.input :name, placeholder: "Name" %>
    </div>
    <div class="macro-new">
      <div style="width: 30%;">
          <%= f.input :protein, placeholder: "Protein" %>
      </div>
      <div style="width: 30%;">
          <%= f.input :carbohydrate, placeholder: "Carbohydrate" %>
      </div>
      <div style="width: 30%;">
          <%= f.input :lipid, placeholder: "Lipid" %>
      </div>
    </div>
    <div class="macro-new">
      <div style="width: 48.5%;">
          <%= f.input :kcal, placeholder: "Kcal" %>
      </div>
      <div style="width: 48.5%">
          <%= f.input :measure, collection: ["ml","gr"]%>
      </div>
    </div>
    <div style="width: 100%;" class="square-button">
      <%= f.submit  %>
    </div>
  <% end %>
</section>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>
<table>
  <tr>
    <td>Protein</td>
    <td>Carbohydrate</td>
    <td>Lipid</td>
    <td>Kcal/100g</td>
  </tr>
    <tr>
      <td><%= @ingredient.protein %></td>
      <td><%= @ingredient.carbohydrate %></td>
      <td><%= @ingredient.lipid %></td>
      <td><%= @ingredient.kcal %></td>
    </tr>
</table>

<%= link_to "Destroy this ingredient" , ingredient_path(@ingredient), data: { turbo_method: :delete, turbo_confirm: "Sure ?" }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookbookAdvanced</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<h1>Change your recipe</h1>

<%= simple_form_for(@recipe) do |f|%>
    <%= f.input :name %>
    <%= f.submit  %>
  <% end %>

<%= link_to "Add a dose to this recipe", new_recipe_dose_path(@recipe) %>
<br>
<li><%= link_to "home", recipes_path()%></li>

app/views/recipes/index.html.erb
<h1>Your recipes</h1>

<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to "#{recipe.name}", recipe_path(recipe) %></li>
  <% end %>
</ul>

<%= simple_form_for(Recipe.new) do |f|%>
    <%= f.input :name %>
    <%= f.submit  %>
  <% end %>

app/views/recipes/new.html.erb
<%= simple_form_for(Recipe.new) do |f|%>
    <%= f.input :name %>
    <%= f.submit  %>
  <% end %>

<li><%= link_to "home", recipes_path()%></li>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<ul>
  <% @recipe.ingredients.each do |ingredient| %>
    <li><%= ingredient.name %>
    <% dose = Dose.find_by(recipe: @recipe, ingredient: ingredient) %><br>
     <%= link_to "delete", dose_path(dose), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove ?"} %>
  <% end %>
</ul>


<br><li><%= link_to "Edit", edit_recipe_path(@recipe) %></li>
<br><li> <%= link_to "delete", recipe_path(@recipe), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></li>
<br><li><%= link_to "home", recipes_path()%></li>